# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: http://dy.paoche.cf/api/v1/client/subscribe?token=52dca2d577d9869cafeeb5fb838a20db
- type: subscribe
  options:
    url: https://api.touhou.center/link/cEYx7YABWJSRWDP9?mu=0
- type: subscribe
  options:
    url: https://jj-rss-01.best/link/INb4pbkPJKvsbHOj?sub=1
- type: subscribe
  options:
    url: https://rxl-nc.xyz/link/uPQKx8YodD56dtvU?sub=3&extend=1
- type: subscribe
  options:
    url: https://www.pacifique.tech/api/v1/client/subscribe?token=fdf70a0411eef8200186f16d8bd0e903
- type: subscribe
  options:
    url: https://www.qcranee.com/link/mIbsDBIDIgCSdflX?sub=1
- type: subscribe
  options:
    url: https://sub.fnf.xyz/link/0yNOBLCxUSubKWOc?list=shadowrocket&extend=1
- type: subscribe
  options:
    url: https://maoxiongnet.com/link/314lSblDykwxN3PU?sub=3&extend=1
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://sub.prprc.xyz/link/7SKAvsSFfj0wPQWz?clash=1

# 某个网站抓取
- type: web-freessrxyz
  options:
