# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
http://dy.paoche.cf/api/v1/client/subscribe?token=52dca2d577d9869cafeeb5fb838a20db
https://api.touhou.center/link/cEYx7YABWJSRWDP9?mu=0
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://sub.prprc.xyz/link/7SKAvsSFfj0wPQWz?clash=1

# 某个网站抓取
- type: web-freessrxyz
  options:
